apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
  namespace: api-service
spec:
  ports:
    - name: api-gateway-svc
      port: 80
      targetPort: 80
  selector:
    app: api-gateway-deploy
  type: ClusterIP