spring:
  config:
    activate:
      on-profile: "prod"

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origin-patterns:
                  - ${PRJ-DOK-ORIGINS}
                allow-credentials: true
                allowed-methods:
                  - PUT
                  - GET
                  - POST
                  - DELETE
                  - OPTIONS
                  - PATCH
          httpclient:
            connect-timeout: ${PROD_HTTP_CLIENT_CONNECT_TIMEOUT}
            response-timeout: ${PROD_HTTP_CLIENT_RESPONSE_TIMEOUT}
          routes:
            - id: PRJ-DOK-FILTER
              uri: ${PRJ-DOK-URI}
              predicates:
                - Path=/dok/**
              filters:
                - RewritePath=/dok/(?<segment>.*), /$\{segment}

            - id: BLOG-FILTER
              uri: ${BLOG-BE-URI}
              predicates:
                - Path=/v1/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: blog-be-cb
                    fallbackUri: forward:/fallback/be
                - name: LocalResponseCache
                  args:
                    size: 5MB
                    timeToLive: 5s

server:
  port: 80

resilience4j:
  circuitbreaker:
    instances:
      blog-be-cb:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 5
        register-health-indicator: true
  timelimiter:
    instances:
      blog-be-cb:
        timeout-duration: 10s
