#kotlin.version=2.2.20
kotlin.code.style=official

org.gradle.jvmargs=-Xmx6g \
  -XX:-UseG1GC \
  -XX:+UseZGC \
  -XX:+HeapDumpOnOutOfMemoryError \
  -XX:+UnlockExperimentalVMOptions \
  -Dfile.encoding=UTF-8 \
  -Djava.awt.headless=true \
  -Dapple.awt.UIElement=true \
  -Dkotlin.daemon.jvm.options="-Xmx4g,-XX:+UseZGC,-Dkotlin.daemon.verbose=true"

org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

kotlin.incremental=true
kotlin.build.report.output=file
kotlin.daemon.useFallbackStrategy=false

org.gradle.vfs.watch=true
org.gradle.vfs.verbose=false

org.gradle.console=verbose
org.gradle.warning.mode=all
