#kotlin.version=2.2.20
kotlin.code.style=official

org.gradle.jvmargs=-Xmx8g \
  -XX:-UseG1GC \
  -XX:+UseZGC \
  -XX:+HeapDumpOnOutOfMemoryError \
  -XX:+UnlockExperimentalVMOptions \
  -XX:+UseLargePages \
  -XX:+UseStringDeduplication \
  -Dfile.encoding=UTF-8 \
  -Djava.awt.headless=true \
  -Dkotlin.daemon.jvm.options="-Xmx6g,-XX:+UseZGC,-XX:+UseTransparentHugePages,-Dkotlin.daemon.verbose=true"


org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.workers.max=16

org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

kotlin.incremental=true
kotlin.build.report.output=file
kotlin.daemon.useFallbackStrategy=false

org.gradle.vfs.watch=true
org.gradle.vfs.verbose=false

org.gradle.console=verbose
org.gradle.warning.mode=all
