name: Lint Check
on:
  push:
    branches: ["feature/*", "feat/*", "features/*"]
    paths: ["application/**", "domain/**", "infrastructure/**", "*.gradle.kts"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "gradle"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint check
        run: ./gradlew ktlintCheck
