name: Run tests
on:
  push:
    branches:
      - "feature/*"
      - "feat/*"
      - "features/*"
    paths:
      - "src/**"
      - "test/**"
      - "*.gradle.kts"
      - "gradle/**"
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'src/**'
            test:
              - 'test/**'
            gradle:
              - 'gradle/**'
              - '*.gradle.kts'

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: "gradle"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Determine test execution
        id: collect
        run: |
          if [ "${{ steps.changes.outputs.gradle }}" == "true" ] ||
             [ "${{ steps.changes.outputs.src }}" == "true" ] ||
             [ "${{ steps.changes.outputs.test }}" == "true" ]; then
            echo "should-test=true" >> $GITHUB_OUTPUT
            echo "modules=test" >> $GITHUB_OUTPUT
          else
            echo "should-test=false" >> $GITHUB_OUTPUT
          fi

      - name: Run tests
        if: steps.collect.outputs.should-test == 'true'
        run: ./gradlew test

      - name: Bundle the build report
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip

      - name: Upload the build report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-report
          path: build-reports.zip
